server {
    listen 80;
    server_name harbor.moein.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name harbor.moein.local;

    ssl_certificate /etc/cert/server.crt;
    ssl_certificate_key /etc/cert/server.key;

    client_max_body_size 1G;

    location / {
        proxy_pass http://portal:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/ {
        proxy_pass http://core:8080;
    }

    location /v2/ {
        proxy_pass http://registry:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
